import { Metadata } from "next";
import "src/styles/root.scss";
import React from "react";
import { Instrument_Sans } from "next/font/google";
import "src/styles/global.css";
import ReduxProvider from "@/providers/redux.provider";
import { SERVER_URL } from "@/const";

export const metadata: Metadata = {
  title: "Frontend Mentor | Link-sharing app - created by Gihwan-dev",
  description: "Generated by create next app",
  viewport: {
    initialScale: 1,
    width: "device-width",
  },
  icons: [
    {
      rel: "icon",
      type: "image/png",
      url: "/icon.png",
      sizes: "32x32",
    },
  ],
};

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({
  login,
  children,
}: {
  login: React.ReactNode;
  children: React.ReactNode;
}) {
  const result = await fetch(`${SERVER_URL}/user`, {
    cache: "no-cache",
    credentials: "include",
  });
  return (
    <html lang="en" className={instrumentSans.className}>
      <body>
        <ReduxProvider>
          {login}
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
